---
title: "European Survey - What is the political sentiment in German speaking Countries Before Covid?"
author: "Milica Pajkic and Marco Rieder"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

# Getting the Data

```{r, include=FALSE}
library(lubridate)
library(multcomp)
library(dplyr)
library(readr)
library(data.table)
library(tidyverse)
```

```{r}
library(readr)
ess9 <- read_delim("ESS9.csv", delim = ",")
```

```{r message=TRUE, paged.print=TRUE}
unique(ess9$name)
unique(ess9$gndr)
unique(ess9$cntry)
```

```{r making subsets of the whole dataset to only german speaking countries}
ess9_de <- subset(ess9, cntry == "DE", select =dweight:domain)
ess9_ch <- subset(ess9, cntry == "CH", select =dweight:domain)
ess9_at <- subset(ess9, cntry == "AT", select =dweight:domain)
```

# 1. Introduction

# 2. Descriptive Statistics

```{r }
summary(ess9_de$nwspol)
sum(is.na(ess9_de$nwspol))
```

```{r echo=FALSE}
summary(ess9_de$gndr)
sum(is.na(ess9_de$gndr))
typeof(ess9_de$nwspol)
```

```{r}
ggplot(ess9_de, aes(nwspol, 1)) +
  geom_bar(stat = "identity") + 
  xlim(c(0, 200))
```

```{r}
boxplot(ess9_de$nwspol, outline=FALSE)
```

### **Was muss man alles für eine deskriptive Analyse machen?**

```{r lineare Regression}
typeof(ess9_de$eduade3)
summary(ess9_de$eduade3)
sum(is.na(ess9_de$eduade3))
```

# 3. Models

## 3.1 Linear Model

How much politics are you watching = DV\
education level by years = IV\
happy with government = IV\
Gender = IV\
Age = IV

```{r linear Regression}
lm_news.1 <- lm(nwspol ~ eduade3, data = ess9_de)
summary(lm_news.1)
```

## 3.2 GLM Poisson

## 3.3 GLM Binominal

## 3.4 GAM

## 3.5 Neural Network

## 3.6 Support Vector Machine
